# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/timofeq/JumpyWiz/CPPsemestr4/vulkan_compute_step1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/timofeq/JumpyWiz/CPPsemestr4/vulkan_compute_step1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timofeq/JumpyWiz/CPPsemestr4/vulkan_compute_step1/CMakeFiles /home/timofeq/JumpyWiz/CPPsemestr4/vulkan_compute_step1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timofeq/JumpyWiz/CPPsemestr4/vulkan_compute_step1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vulkan_minimal_compute

# Build rule for target.
vulkan_minimal_compute: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vulkan_minimal_compute
.PHONY : vulkan_minimal_compute

# fast build rule for target.
vulkan_minimal_compute/fast:
	$(MAKE) -f CMakeFiles/vulkan_minimal_compute.dir/build.make CMakeFiles/vulkan_minimal_compute.dir/build
.PHONY : vulkan_minimal_compute/fast

src/Bitmap.o: src/Bitmap.cpp.o

.PHONY : src/Bitmap.o

# target to build an object file
src/Bitmap.cpp.o:
	$(MAKE) -f CMakeFiles/vulkan_minimal_compute.dir/build.make CMakeFiles/vulkan_minimal_compute.dir/src/Bitmap.cpp.o
.PHONY : src/Bitmap.cpp.o

src/Bitmap.i: src/Bitmap.cpp.i

.PHONY : src/Bitmap.i

# target to preprocess a source file
src/Bitmap.cpp.i:
	$(MAKE) -f CMakeFiles/vulkan_minimal_compute.dir/build.make CMakeFiles/vulkan_minimal_compute.dir/src/Bitmap.cpp.i
.PHONY : src/Bitmap.cpp.i

src/Bitmap.s: src/Bitmap.cpp.s

.PHONY : src/Bitmap.s

# target to generate assembly for a file
src/Bitmap.cpp.s:
	$(MAKE) -f CMakeFiles/vulkan_minimal_compute.dir/build.make CMakeFiles/vulkan_minimal_compute.dir/src/Bitmap.cpp.s
.PHONY : src/Bitmap.cpp.s

src/bilateral.o: src/bilateral.cpp.o

.PHONY : src/bilateral.o

# target to build an object file
src/bilateral.cpp.o:
	$(MAKE) -f CMakeFiles/vulkan_minimal_compute.dir/build.make CMakeFiles/vulkan_minimal_compute.dir/src/bilateral.cpp.o
.PHONY : src/bilateral.cpp.o

src/bilateral.i: src/bilateral.cpp.i

.PHONY : src/bilateral.i

# target to preprocess a source file
src/bilateral.cpp.i:
	$(MAKE) -f CMakeFiles/vulkan_minimal_compute.dir/build.make CMakeFiles/vulkan_minimal_compute.dir/src/bilateral.cpp.i
.PHONY : src/bilateral.cpp.i

src/bilateral.s: src/bilateral.cpp.s

.PHONY : src/bilateral.s

# target to generate assembly for a file
src/bilateral.cpp.s:
	$(MAKE) -f CMakeFiles/vulkan_minimal_compute.dir/build.make CMakeFiles/vulkan_minimal_compute.dir/src/bilateral.cpp.s
.PHONY : src/bilateral.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/vulkan_minimal_compute.dir/build.make CMakeFiles/vulkan_minimal_compute.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/vulkan_minimal_compute.dir/build.make CMakeFiles/vulkan_minimal_compute.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/vulkan_minimal_compute.dir/build.make CMakeFiles/vulkan_minimal_compute.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/vk_utils.o: src/vk_utils.cpp.o

.PHONY : src/vk_utils.o

# target to build an object file
src/vk_utils.cpp.o:
	$(MAKE) -f CMakeFiles/vulkan_minimal_compute.dir/build.make CMakeFiles/vulkan_minimal_compute.dir/src/vk_utils.cpp.o
.PHONY : src/vk_utils.cpp.o

src/vk_utils.i: src/vk_utils.cpp.i

.PHONY : src/vk_utils.i

# target to preprocess a source file
src/vk_utils.cpp.i:
	$(MAKE) -f CMakeFiles/vulkan_minimal_compute.dir/build.make CMakeFiles/vulkan_minimal_compute.dir/src/vk_utils.cpp.i
.PHONY : src/vk_utils.cpp.i

src/vk_utils.s: src/vk_utils.cpp.s

.PHONY : src/vk_utils.s

# target to generate assembly for a file
src/vk_utils.cpp.s:
	$(MAKE) -f CMakeFiles/vulkan_minimal_compute.dir/build.make CMakeFiles/vulkan_minimal_compute.dir/src/vk_utils.cpp.s
.PHONY : src/vk_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... vulkan_minimal_compute"
	@echo "... edit_cache"
	@echo "... src/Bitmap.o"
	@echo "... src/Bitmap.i"
	@echo "... src/Bitmap.s"
	@echo "... src/bilateral.o"
	@echo "... src/bilateral.i"
	@echo "... src/bilateral.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/vk_utils.o"
	@echo "... src/vk_utils.i"
	@echo "... src/vk_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

